modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "inventory_trash_can"
version = "${version}"
displayName = "Inventory Trash Can"
logoFile = "assets/inventory_trash_can/icon.png"
authors = "Cukkoo"
description = '''
A mod that allows for the quick and practical disposal of unnecessary items directly from the Minecraft inventory.
'''

[[dependencies.inventory_trash_can]]
modId = "neoforge"
mandatory = true
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.inventory_trash_can]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.4]"
ordering = "NONE"
side = "BOTH"
